image: node

cache:
  paths:
    - node_modules/

before_script:
  - npm install

all_tests:
  stage: test
  script:
    - npm run lint
    - npm run test
  coverage: '/^All files[ ]*\|[ ]*([\d]+)[ ]*\|/'
